### ISSUE TITLE
Error：  AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by pendave** [2Dou/watermarker#1]
Traceback (most recent call last):
  File "marker.py", line 142, in <module>
    main()
  File "marker.py", line 129, in main
    args.mark = args.mark.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

**Comment by pendave** [comment]
![_20180928164236](https://user-images.githubusercontent.com/1331881/46197894-9e3cb480-c33d-11e8-9ee1-47ac41c9f01a.png)

**Comment by Raven-Lee** [comment]
我有一样的问题, 请问你的问题解决了吗?

**Comment by Raven-Lee** [comment]
把truetype的调用改成windows系统内任意字体名字即可. 下面我用的是宋体.
`    # 生成文字
    draw_table = ImageDraw.Draw(im=mark)
    draw_table.text(xy=(0, 0),
                    text=args.mark,
                    fill=args.color,
                    font=ImageFont.truetype('simsun.ttc',
                                            size=args.size))`
