### ISSUE TITLE
当给超清图片进行加水印的时候, 处理后的图片会旋转90度 (我测试图片的体积是 26 MB)

### ISSUE THREAD

**Issue by e2366705** [2Dou/watermarker#8]
如题:  加水印后的图片会旋转90度数, 加上 --quality=100 还是无济于事,  我测试图片的体积是 26 MB, 当时用单反拍出来的

**Comment by e2366705** [comment]
另外, 我的测试平台是 Windows 10 系统

**Comment by e2366705** [comment]
还有  一些小图片是正常的, 没有出现旋转的情况, 比如几百KB的小图片

**Comment by 2Dou** [comment]
> 如题: 加水印后的图片会旋转90度数, 加上 --quality=100 还是无济于事, 我测试图片的体积是 26 MB, 当时用单反拍出来的

重新试试旋转问题解决了吗？

**Comment by e2366705** [comment]
> > 如题: 加水印后的图片会旋转90度数, 加上 --quality=100 还是无济于事, 我测试图片的体积是 26 MB, 当时用单反拍出来的
> 
> 重新试试旋转问题解决了吗？

ok , 经测试没问题了, 非常感谢 ~
